---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xin.an.
--- DateTime: 2026/8/6 10:06
---

local current = tonumber(redis.call('GET', KEYS[1]) or '0')
if current >= tonumber(ARGV[1]) then
    return 0
end
redis.call('INCR', KEYS[1])
redis.call('EXPIRE', KEYS[1], tonumber(ARGV[2]))
return 1