---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xin.an.
--- DateTime: 2026/8/6 10:19
---

local current = tonumber(redis.call('GET', KEYS[1]) or '0')
if current > 0 then
    redis.call('DECR', KEYS[1])
end
return current - 1