<template>
  <div class="app">
    <aside v-if="state.me" class="sidebar">
      <div class="brand"><b>P</b><span>pyclaw</span></div>
      <button v-for="item in visibleNav" :key="item.key" :class="{active:state.view===item.key}" @click="setView(item.key)">{{ item.icon }} {{ item.label }}</button>
    </aside>
    <main :class="['main',{centered:!state.me}]">
      <form v-if="!state.me" class="panel login" @submit.prevent="login">
        <h1>pyclaw Console</h1><p>Control plane for providers, channels, agents, tools, and routes.</p>
        <label>Backend URL<input v-model="state.apiBase" placeholder="empty for same-origin" /></label>
        <label>Username<input v-model="loginForm.username" /></label>
        <label>Password<input v-model="loginForm.password" type="password" /></label>
        <button class="primary">Sign in</button><p class="error">{{ state.error }}</p>
      </form>
      <template v-else>
        <header class="topbar"><div><p>{{ currentTitle }}</p><h1>{{ currentSubtitle }}</h1></div><div><b>{{ state.me.username }}</b><button @click="logout">Logout</button></div></header>
        <div v-if="state.error" class="toast error">{{ state.error }}<button @click="state.error=''">Close</button></div>
        <div v-if="state.notice" class="toast ok">{{ state.notice }}<button @click="state.notice=''">Close</button></div>
        <section v-if="state.view==='dashboard'" class="stack"><div class="metrics"><article><span>Backend</span><b>{{ dashboard.health }}</b></article><article><span>User</span><b>{{ state.me.username }}</b></article><article><span>Runs</span><b>{{ usageStats.totalRuns }}</b></article><article><span>Tokens</span><b>{{ usageStats.totalTokens }}</b></article></div><Panel title="Authorities"><div class="chips"><span v-for="a in state.me.authorities" :key="a">{{ a }}</span></div></Panel></section>
        <section v-if="state.view==='agent'" class="grid"><form class="panel" @submit.prevent="runAgent"><h2>Agent Playground</h2><label>Prompt<textarea v-model="agentForm.prompt" /></label><label>Provider<input v-model="agentForm.provider" /></label><label>Model<input v-model="agentForm.model" /></label><label>Session<input v-model="agentForm.sessionId" /></label><label>Tool Profile<select v-model="agentForm.toolProfile"><option v-for="p in toolProfiles" :key="p">{{ p }}</option></select></label><button class="primary">Run</button></form><Panel title="Response"><pre>{{ agentResult.text || 'Waiting for result' }}</pre><details><summary>Raw JSON</summary><pre>{{ pretty(agentResult.raw) }}</pre></details></Panel></section>
        <section v-if="state.view==='tokens'" class="stack"><form class="panel form" @submit.prevent="createToken"><h2>Create Token</h2><label>Name<input v-model="tokenForm.name" /></label><label>Expires<input v-model="tokenForm.expiresAt" /></label><label>Scopes<input v-model="tokenForm.scopes" /></label><button class="primary">Create</button></form><DataTable title="Tokens" :rows="tokens" :columns="tokenColumns"><template #actions="{row}"><button class="danger" @click="revokeToken(row.id)">Revoke</button></template></DataTable></section>
        <section v-if="state.view==='users'" class="stack"><form class="panel form" @submit.prevent="createUser"><h2>Create User</h2><label>Username<input v-model="userForm.username" /></label><label>Password<input v-model="userForm.password" type="password" /></label><label>Display<input v-model="userForm.displayName" /></label><label>Authorities<input v-model="userForm.authorities" /></label><button class="primary">Create</button></form><DataTable title="Users" :rows="users" :columns="userColumns"><template #actions="{row}"><button class="danger" @click="disableUser(row.id)">Disable</button></template></DataTable></section>
        <section v-if="state.view==='providers'" class="stack"><form class="panel form" @submit.prevent="saveProvider"><h2>{{ providerForm.id?'Edit':'Create' }} Provider</h2><label>Name<input v-model="providerForm.name" /></label><label>Type<input v-model="providerForm.providerType" /></label><label>Base URL<input v-model="providerForm.baseUrl" /></label><label>Model<input v-model="providerForm.model" /></label><label>API Mode<select v-model="providerForm.apiMode"><option>chat_completions</option><option>responses</option><option>auto</option></select></label><label>Secret Ref<input v-model="providerForm.secretRef" /></label><label>API Key<input v-model="providerForm.apiKey" type="password" /></label><label><input v-model="providerForm.enabled" type="checkbox" /> Enabled</label><label v-if="providerForm.id&&providerForm.apiKeyConfigured"><input v-model="providerForm.clearApiKey" type="checkbox" /> Clear key</label><button class="primary">Save</button><button type="button" @click="resetProviderForm">Reset</button></form><DataTable title="Providers" :rows="providers" :columns="providerColumns"><template #actions="{row}"><button @click="editProvider(row)">Edit</button><button class="danger" @click="deleteProvider(row.id)">Delete</button></template></DataTable></section>
        <section v-if="state.view==='channels'" class="stack"><form class="panel form" @submit.prevent="saveChannel"><h2>{{ channelForm.id?'Edit':'Create' }} Channel</h2><label>Type<select v-model="channelForm.channelType"><option>wechat</option><option>feishu</option></select></label><label>Name<input v-model="channelForm.name" /></label><label>Secret Ref<input v-model="channelForm.secretRef" /></label><label>Reply Mode<select v-model="channelForm.replyMode"><option v-for="m in channelReplyModes" :key="m.value" :value="m.value">{{ m.label }}</option></select></label><label><input v-model="channelForm.enabled" type="checkbox" /> Enabled</label><label>Config JSON<textarea v-model="channelForm.configJson" /></label><button class="primary">Save</button><button type="button" @click="resetChannelForm">Reset</button></form><DataTable title="Channels" :rows="channels" :columns="channelColumns"><template #actions="{row}"><button @click="editChannel(row)">Edit</button><button class="danger" @click="deleteChannel(row.id)">Delete</button></template></DataTable></section>
        <section v-if="state.view==='agents'" class="stack"><form class="panel form" @submit.prevent="saveAgent"><h2>{{ agentForm2.id?'Edit':'Create' }} Agent</h2><label>Key<input v-model="agentForm2.agentKey" /></label><label>Name<input v-model="agentForm2.name" /></label><label>Provider<input v-model="agentForm2.provider" /></label><label>Provider Config<select v-model="agentForm2.providerId"><option value="">Environment</option><option v-for="p in providerOptions" :key="p.id" :value="p.id">{{ p.name }} - {{ p.model }}</option></select></label><label>Model<input v-model="agentForm2.model" /></label><label>Workspace<input v-model="agentForm2.workspaceDir" /></label><label>Profile<select v-model="agentForm2.toolProfile"><option v-for="p in toolProfiles" :key="p">{{ p }}</option></select></label><label>Shell Approval<select v-model="agentForm2.shellApproval"><option>deny</option><option>require</option><option>auto</option></select></label><label><input v-model="agentForm2.enabled" type="checkbox" /> Enabled</label><label><input v-model="agentForm2.readonly" type="checkbox" /> Readonly</label><label><input v-model="agentForm2.workspaceOnly" type="checkbox" /> Workspace only</label><label><input v-model="agentForm2.webAccess" type="checkbox" /> Web access</label><label>Description<input v-model="agentForm2.description" /></label><label>System<textarea v-model="agentForm2.systemPrompt" /></label><label>Allow<input v-model="agentForm2.toolsAllow" /></label><label>Deny<input v-model="agentForm2.toolsDeny" /></label><label>Also Allow<input v-model="agentForm2.toolsAlsoAllow" /></label><button class="primary">Save</button><button type="button" @click="resetAgentForm">Reset</button></form><DataTable title="Agents" :rows="agents" :columns="agentColumns"><template #actions="{row}"><button @click="editAgent(row)">Edit</button><button class="danger" @click="deleteAgent(row.id)">Delete</button></template></DataTable></section>
        <section v-if="state.view==='tools'" class="stack"><form class="panel form" @submit.prevent="previewTools"><h2>Effective Tools</h2><label>Profile<select v-model="toolForm.profile"><option v-for="p in toolProfiles" :key="p">{{ p }}</option></select></label><label>Allow<input v-model="toolForm.allow" /></label><label>Deny<input v-model="toolForm.deny" /></label><label>Also Allow<input v-model="toolForm.alsoAllow" /></label><label><input v-model="toolForm.readonly" type="checkbox" /> Readonly</label><button class="primary">Preview</button><textarea :value="toolPreview.effectiveTools.join(', ')" readonly /></form><DataTable title="Tool Catalog" :rows="toolCatalog" :columns="toolColumns" /></section>
        <section v-if="state.view==='routes'" class="stack"><form class="panel form" @submit.prevent="saveRoute"><h2>{{ routeForm.id?'Edit':'Create' }} Route</h2><label>Agent<select v-model="routeForm.agentId"><option value="">Select</option><option v-for="a in agents" :key="a.id" :value="a.id">{{ a.agentKey }} - {{ a.name }}</option></select></label><label>Priority<input v-model.number="routeForm.priority" type="number" /></label><label>Channel<input v-model="routeForm.channel" /></label><label>Account<input v-model="routeForm.accountId" /></label><label>Peer Kind<select v-model="routeForm.peerKind"><option value="">Any</option><option>direct</option><option>group</option><option>channel</option><option>thread</option></select></label><label>Peer ID<input v-model="routeForm.peerId" /></label><label>Mention Aliases<input v-model="routeForm.mentionAliases" /></label><label>Command Prefixes<input v-model="routeForm.commandPrefixes" /></label><label>Sender IDs<input v-model="routeForm.senderIds" /></label><label>DM Scope<select v-model="routeForm.dmScope"><option>main</option><option>per-peer</option><option>per-channel-peer</option><option>per-account-channel-peer</option></select></label><label><input v-model="routeForm.enabled" type="checkbox" /> Enabled</label><label>Comment<input v-model="routeForm.comment" /></label><button class="primary">Save</button><button type="button" @click="resetRouteForm">Reset</button></form><DataTable title="Routes" :rows="routes" :columns="routeColumns"><template #actions="{row}"><button @click="editRoute(row)">Edit</button><button class="danger" @click="deleteRoute(row.id)">Delete</button></template></DataTable></section>
        <section v-if="state.view==='audit'" class="stack"><DataTable title="Audit" :rows="auditLogs" :columns="auditColumns" /></section>
        <section v-if="state.view==='usage'" class="stack"><DataTable title="Usage" :rows="usageRecords" :columns="usageColumns" /></section>
      </template>
    </main>
    <div v-if="createdToken.token" class="modal"><section><h2>{{ createdToken.tokenId }}</h2><pre>{{ createdToken.token }}</pre><button @click="copy(createdToken.token)">Copy</button><button class="primary" @click="createdToken.token=''">Saved</button></section></div>
  </div>
</template>

<script setup>
import { computed, h, onMounted, reactive, ref } from 'vue';
const TOKEN_KEY='pyclaw.console.token', BASE_KEY='pyclaw.console.baseUrl';
const nav=[['dashboard','Overview','01'],['agent','Run','02','agent:run'],['tokens','Tokens','03','token:manage_self'],['users','Users','04','user:manage'],['providers','Providers','05','provider:manage'],['channels','Channels','06','channel:manage'],['agents','Agents','07','agent:read'],['tools','Tools','08','tool:catalog:read'],['routes','Routes','09','agent:route:manage'],['audit','Audit','10','audit:read'],['usage','Usage','11','audit:read']].map(([key,label,icon,authority])=>({key,label,icon,authority}));
const state=reactive({apiBase:localStorage.getItem(BASE_KEY)||'',token:localStorage.getItem(TOKEN_KEY)||'',me:null,view:'dashboard',loading:false,error:'',notice:''});
const loginForm=reactive({username:'admin',password:''}), dashboard=reactive({health:'unknown'}), createdToken=reactive({tokenId:'',token:''});
const agentForm=reactive({prompt:'hello',provider:'openai',sessionId:'web-demo',toolProfile:'minimal',model:''}), agentResult=reactive({text:'',raw:null});
const tokenForm=reactive({name:'frontend-token',expiresAt:'',scopes:'agent:run'}), userForm=reactive({username:'',password:'',displayName:'',authorities:'agent:run,agent:read,token:manage_self'});
const providerForm=reactive(defProvider()), channelForm=reactive(defChannel()), agentForm2=reactive(defAgent()), toolForm=reactive({profile:'coding',allow:'',deny:'',alsoAllow:'',readonly:false}), routeForm=reactive(defRoute());
const tokens=ref([]),users=ref([]),providers=ref([]),providerOptions=ref([]),channels=ref([]),agents=ref([]),toolCatalog=ref([]),routes=ref([]),auditLogs=ref([]),usageRecords=ref([]),toolProfiles=ref(['minimal','readonly','messaging','coding','full']);
const toolPreview=reactive({effectiveTools:[],deniedTools:[]});
const visibleNav=computed(()=>nav.filter(i=>!i.authority||has(i.authority))), currentTitle=computed(()=>nav.find(i=>i.key===state.view)?.label||'Console'), currentSubtitle=computed(()=>({dashboard:'System status',agent:'Run agent',tokens:'API tokens',users:'Users',providers:'Providers',channels:'Channels',agents:'Agent registry',tools:'Tool policy preview',routes:'Route bindings',audit:'Audit logs',usage:'Usage records'}[state.view]||''));
const channelReplyModes=computed(()=>channelForm.channelType==='wechat'?[{value:'passive_xml',label:'Passive XML'},{value:'async_worker',label:'Async Worker'}]:[{value:'async_worker',label:'Async Worker'}]);
const usageStats=computed(()=>({totalRuns:usageRecords.value.length,totalTokens:usageRecords.value.reduce((s,r)=>s+Number(r.totalTokens||0),0)}));
const tokenColumns=['name','scopes','expiresAt','revokedAt','createdAt'], userColumns=['username','displayName','status','authorities'], providerColumns=['name','providerType','baseUrl','model','apiMode','apiKeyConfigured','enabled'], channelColumns=['channelType','name','secretRef','enabled','updatedAt'];
const agentColumns=['agentKey','name','providerConfigName','provider','model','workspaceDir','enabled'], toolColumns=['name','sectionId','profiles','tags','risk'], routeColumns=['priority','agentKey','channel','accountId','peerKind','peerId','mentionAliases','commandPrefixes','dmScope','enabled'], auditColumns=['createdAt','actorType','actorId','action','resourceType','resourceId','success'], usageColumns=['createdAt','sessionId','provider','model','totalTokens','success','latencyMs'];
const Panel={props:{title:String},setup(p,{slots}){return()=>h('article',{class:'panel'},[h('h2',p.title),slots.default?.()])}};
const DataTable={props:{title:String,rows:Array,columns:Array},setup(p,{slots}){const cell=v=>v==null||v===''?'-':typeof v==='object'?JSON.stringify(v):String(v);return()=>h('article',{class:'panel table'},[h('h2',`${p.title} (${p.rows.length})`),h('div',{class:'scroll'},[h('table',[h('thead',[h('tr',[...p.columns.map(c=>h('th',c)),slots.actions?h('th','Actions'):null])]),h('tbody',p.rows.length?p.rows.map(r=>h('tr',{key:r.id||JSON.stringify(r)},[...p.columns.map(c=>h('td',cell(r[c]))),slots.actions?h('td',slots.actions({row:r})):null])):[h('tr',[h('td',{colspan:p.columns.length+(slots.actions?1:0)},'No data')])])])])])}};
onMounted(()=>{if(state.token)loadMe()});
function defProvider(){return{id:'',name:'',providerType:'openai-compatible',baseUrl:'https://api.deepseek.com',model:'deepseek-chat',apiMode:'chat_completions',secretRef:'pyclaw-provider-secret',apiKey:'',clearApiKey:false,apiKeyConfigured:false,enabled:true}}
function defChannel(){return{id:'',channelType:'wechat',name:'',configJson:'{\n  "callbackPath": "/api/webhooks/wechat",\n  "reply_mode": "passive_xml"\n}',replyMode:'passive_xml',secretRef:'',enabled:true}}
function defAgent(){return{id:'',agentKey:'default',name:'Default Agent',description:'',enabled:true,providerId:'',provider:'openai',model:'',systemPrompt:'',workspaceDir:'',runtimeType:'agent_session',toolProfile:'messaging',toolsAllow:'',toolsDeny:'',toolsAlsoAllow:'',workspaceOnly:true,readonly:false,shellApproval:'deny',webAccess:false}}
function defRoute(){return{id:'',enabled:true,priority:0,agentId:'',channel:'feishu',accountId:'',peerKind:'',peerId:'',mentionAliases:'',commandPrefixes:'',senderIds:'',dmScope:'per-account-channel-peer',comment:''}}
function has(a){return Boolean(state.me?.authorities?.includes(a))} function ep(p){return`${state.apiBase.trim().replace(/\/$/,'')}${p}`}
async function api(path,opt={}){const headers={...(opt.headers||{})};if(!(opt.body instanceof FormData))headers['Content-Type']=headers['Content-Type']||'application/json';if(state.token)headers.Authorization=`Bearer ${state.token}`;const r=await fetch(ep(path),{...opt,headers});if(!r.ok)throw new Error(await err(r));if(r.status===204)return null;const t=await r.text();return t?JSON.parse(t):null}
async function err(r){const t=await r.text();try{const d=JSON.parse(t);return d.message||d.detail||t}catch{return t||`${r.status} ${r.statusText}`}}
async function login(){await load(async()=>{localStorage.setItem(BASE_KEY,state.apiBase.trim());const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({username:loginForm.username,password:loginForm.password})});state.token=d.accessToken;localStorage.setItem(TOKEN_KEY,state.token);await loadMe()})}
async function loadMe(){try{state.me=await api('/api/auth/me');await refresh()}catch(e){state.me=null;state.token='';localStorage.removeItem(TOKEN_KEY);state.error=e.message}}
function logout(){state.me=null;state.token='';localStorage.removeItem(TOKEN_KEY)} async function setView(v){state.view=v;await refresh()}
async function refresh(){const m={dashboard:dash,tokens:loadTokens,users:loadUsers,providers:loadProviders,channels:loadChannels,agents:loadAgents,tools:loadTools,routes:loadRoutes,audit:()=>fetchRows('/api/audit-logs',auditLogs),usage:()=>fetchRows('/api/usage-records',usageRecords)};if(m[state.view])await m[state.view]()}
async function dash(){await safe(async()=>{try{dashboard.health=(await api(state.apiBase.trim()?'/healthz':'/backend-healthz'))?.status||'ok'}catch{dashboard.health='unavailable'}if(has('audit:read'))await fetchRows('/api/usage-records',usageRecords)})}
async function runAgent(){await load(async()=>{const d=await api('/api/agent/run',{method:'POST',body:JSON.stringify({prompt:agentForm.prompt,provider:agentForm.provider,sessionId:agentForm.sessionId,toolProfile:agentForm.toolProfile,model:agentForm.model||undefined})});agentResult.text=d.text||'';agentResult.raw=d})}
async function fetchRows(path,refv){await safe(async()=>{refv.value=await api(path)})} async function loadTokens(){return fetchRows('/api/tokens',tokens)} async function loadUsers(){return fetchRows('/api/users',users)} async function loadProviderOptions(){return fetchRows('/api/providers/options',providerOptions)} async function loadProviders(){await fetchRows('/api/providers',providers);providerOptions.value=providers.value.map(p=>({id:p.id,name:p.name,providerType:p.providerType,model:p.model,apiMode:p.apiMode,enabled:p.enabled}))} async function loadChannels(){return fetchRows('/api/channels',channels)}
async function createToken(){await load(async()=>{const d=await api('/api/tokens',{method:'POST',body:JSON.stringify({name:tokenForm.name,expiresAt:tokenForm.expiresAt||null,scopes:csv(tokenForm.scopes)})});createdToken.tokenId=d.tokenId;createdToken.token=d.token;await loadTokens()})}
async function revokeToken(id){if(confirm('Revoke token?'))await load(async()=>{await api(`/api/tokens/${id}`,{method:'DELETE'});await loadTokens()})}
async function createUser(){await load(async()=>{await api('/api/users',{method:'POST',body:JSON.stringify(userForm)});Object.assign(userForm,{username:'',password:'',displayName:'',authorities:userForm.authorities});await loadUsers()})} async function disableUser(id){if(confirm('Disable user?'))await load(async()=>{await api(`/api/users/${id}/disable`,{method:'PUT'});await loadUsers()})}
function editProvider(r){Object.assign(providerForm,r,{apiKey:'',clearApiKey:false})} function resetProviderForm(){Object.assign(providerForm,defProvider())}
async function saveProvider(){await load(async()=>{const p={name:providerForm.name,providerType:providerForm.providerType,baseUrl:providerForm.baseUrl||null,model:providerForm.model,apiMode:providerForm.apiMode,secretRef:providerForm.secretRef||null,apiKey:providerForm.apiKey||null,clearApiKey:providerForm.clearApiKey,enabled:providerForm.enabled};await api(providerForm.id?`/api/providers/${providerForm.id}`:'/api/providers',{method:providerForm.id?'PUT':'POST',body:JSON.stringify(p)});resetProviderForm();await loadProviders();await loadProviderOptions()})} async function deleteProvider(id){if(confirm('Delete provider?'))await load(async()=>{await api(`/api/providers/${id}`,{method:'DELETE'});await loadProviders();await loadProviderOptions()})}
function editChannel(r){const cfg=parse(r.configJson||'{}');Object.assign(channelForm,{...r,replyMode:cfg.reply_mode||'async_worker',configJson:fmt(r.configJson)})} function resetChannelForm(){Object.assign(channelForm,defChannel())}
async function saveChannel(){await load(async()=>{const cfg=parse(channelForm.configJson);cfg.reply_mode=channelForm.replyMode;await api(channelForm.id?`/api/channels/${channelForm.id}`:'/api/channels',{method:channelForm.id?'PUT':'POST',body:JSON.stringify({channelType:channelForm.channelType,name:channelForm.name,config:cfg,secretRef:channelForm.secretRef||null,enabled:channelForm.enabled})});resetChannelForm();await loadChannels()})} async function deleteChannel(id){if(confirm('Delete channel?'))await load(async()=>{await api(`/api/channels/${id}`,{method:'DELETE'});await loadChannels()})}
async function loadAgents(){await safe(async()=>{if(!providerOptions.value.length)await loadProviderOptions();const rows=await api('/api/agents');agents.value=rows.map(enrichAgent)})} function enrichAgent(agent){return{...agent,providerConfigName:providerOptionName(agent.providerId)}} function providerOptionName(id){if(!id)return 'Environment';const p=providerOptions.value.find(x=>x.id===id);return p?p.name+' ('+p.model+')':'Unknown provider'} function resetAgentForm(){Object.assign(agentForm2,defAgent())}
function editAgent(r){const p=r.toolPolicy||{};Object.assign(agentForm2,{...defAgent(),...r,toolProfile:p.profile||'messaging',toolsAllow:(p.toolsAllow||[]).join(','),toolsDeny:(p.toolsDeny||[]).join(','),toolsAlsoAllow:(p.toolsAlsoAllow||[]).join(','),workspaceOnly:p.workspaceOnly??true,readonly:p.readonly??false,shellApproval:p.shellApproval||'deny',webAccess:p.webAccess??false})}
function agentPayload(){return{agentKey:agentForm2.agentKey,name:agentForm2.name,description:agentForm2.description||null,enabled:agentForm2.enabled,providerId:agentForm2.providerId||null,provider:agentForm2.provider||null,model:agentForm2.model||null,systemPrompt:agentForm2.systemPrompt||null,workspaceDir:agentForm2.workspaceDir||null,runtimeType:agentForm2.runtimeType,toolPolicy:{profile:agentForm2.toolProfile,toolsAllow:empty(agentForm2.toolsAllow),toolsDeny:csv(agentForm2.toolsDeny),toolsAlsoAllow:csv(agentForm2.toolsAlsoAllow),workspaceOnly:agentForm2.workspaceOnly,readonly:agentForm2.readonly,shellApproval:agentForm2.shellApproval,webAccess:agentForm2.webAccess}}}
async function saveAgent(){await load(async()=>{await api(agentForm2.id?`/api/agents/${agentForm2.id}`:'/api/agents',{method:agentForm2.id?'PUT':'POST',body:JSON.stringify(agentPayload())});resetAgentForm();await loadAgents()})} async function deleteAgent(id){if(confirm('Delete agent?'))await load(async()=>{await api(`/api/agents/${id}`,{method:'DELETE'});await loadAgents()})}
async function loadTools(){await safe(async()=>{toolProfiles.value=await api('/api/tools/profiles');toolCatalog.value=await api('/api/tools/catalog');await previewTools()})} async function previewTools(){await safe(async()=>{const d=await api('/api/tools/effective',{method:'POST',body:JSON.stringify({profile:toolForm.profile,allow:empty(toolForm.allow),deny:csv(toolForm.deny),alsoAllow:csv(toolForm.alsoAllow),readonly:toolForm.readonly})});toolPreview.effectiveTools=d.effectiveTools||[];toolPreview.deniedTools=d.deniedTools||[]})}
async function loadRoutes(){await safe(async()=>{if(!agents.value.length)await loadAgents();routes.value=await api('/api/route-bindings')})} function resetRouteForm(){Object.assign(routeForm,defRoute())} function editRoute(r){Object.assign(routeForm,{...defRoute(),...r,mentionAliases:(r.mentionAliases||[]).join(','),commandPrefixes:(r.commandPrefixes||[]).join(','),senderIds:(r.senderIds||[]).join(',')})}
function routePayload(){return{enabled:routeForm.enabled,priority:routeForm.priority,agentId:routeForm.agentId,channel:routeForm.channel||null,accountId:routeForm.accountId||null,peerKind:routeForm.peerKind||null,peerId:routeForm.peerId||null,mentionAliases:csv(routeForm.mentionAliases),commandPrefixes:csv(routeForm.commandPrefixes),senderIds:csv(routeForm.senderIds),dmScope:routeForm.dmScope,comment:routeForm.comment||null}}
async function saveRoute(){await load(async()=>{await api(routeForm.id?`/api/route-bindings/${routeForm.id}`:'/api/route-bindings',{method:routeForm.id?'PUT':'POST',body:JSON.stringify(routePayload())});resetRouteForm();await loadRoutes()})} async function deleteRoute(id){if(confirm('Delete route?'))await load(async()=>{await api(`/api/route-bindings/${id}`,{method:'DELETE'});await loadRoutes()})}
function csv(v){return String(v||'').split(',').map(x=>x.trim()).filter(Boolean)} function empty(v){const a=csv(v);return a.length?a:null} function parse(v){try{return String(v||'').trim()?JSON.parse(v):{}}catch{throw new Error('Invalid JSON')}} function fmt(v){try{return JSON.stringify(typeof v==='string'?JSON.parse(v):v,null,2)}catch{return v||'{}'}} function pretty(v){return v?JSON.stringify(v,null,2):'{}'} async function copy(v){await navigator.clipboard?.writeText(v)}
async function load(fn){state.loading=true;await safe(fn);state.loading=false} async function safe(fn){state.error='';try{await fn()}catch(e){state.error=e.message||String(e)}finally{state.loading=false}} function notice(m){state.notice=m;setTimeout(()=>{if(state.notice===m)state.notice=''},2500)}
</script>
<style>
body{margin:0;background:#f3f5f7;color:#17202d;font-family:Inter,system-ui,Segoe UI,sans-serif}*{box-sizing:border-box}button,input,select,textarea{font:inherit}button{border:1px solid #c8d0da;border-radius:6px;background:white;padding:.5rem .75rem;cursor:pointer}.primary{background:#0f766e;border-color:#0f766e;color:white;font-weight:700}.danger{color:#9f1d20}.app{min-height:100vh;display:grid;grid-template-columns:230px 1fr}.sidebar{background:#152130;color:#e6edf5;padding:1rem;display:flex;flex-direction:column;gap:.35rem}.brand{display:flex;gap:.6rem;align-items:center;margin-bottom:1rem}.brand b{background:#2bb19f;color:white;border-radius:8px;width:36px;height:36px;display:grid;place-items:center}.sidebar button{background:transparent;color:#cbd5e1;border-color:transparent;text-align:left}.sidebar button.active,.sidebar button:hover{background:#25354a;color:white}.main{padding:1.25rem;min-width:0}.centered{grid-column:1/-1;display:grid;place-items:center}.login{width:min(460px,100%)}.topbar{display:flex;justify-content:space-between;align-items:center;margin:0 auto 1rem;max-width:1440px}.topbar h1{margin:.1rem 0 0}.topbar p{margin:0;color:#66778c;text-transform:uppercase;font-size:.8rem}.stack,.grid{max-width:1440px;margin:0 auto}.stack{display:grid;gap:1rem}.grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.panel,.metrics article{background:white;border:1px solid #dce2ea;border-radius:8px;padding:1rem}.form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.75rem}.form h2,.form button,.form textarea{grid-column:1/-1}label{display:grid;gap:.3rem;font-weight:650;color:#405066}input,select,textarea{width:100%;border:1px solid #c8d0da;border-radius:6px;padding:.55rem}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:1rem}.metrics span{display:block;color:#66778c}.metrics b{font-size:1.5rem}.chips{display:flex;flex-wrap:wrap;gap:.4rem}.chips span{border:1px solid #c8d0da;border-radius:999px;padding:.25rem .55rem}.toast{max-width:1440px;margin:0 auto 1rem;padding:.75rem;border-radius:8px;display:flex;justify-content:space-between}.error{color:#9f1d20}.ok{background:#edf8f4;color:#116a5b}.scroll{overflow:auto}table{width:100%;border-collapse:collapse;min-width:820px}th,td{border-bottom:1px solid #e4e9ef;padding:.65rem;text-align:left;vertical-align:top;max-width:300px;overflow-wrap:anywhere}th{background:#f8fafc;color:#66778c}pre{background:#111827;color:#e5e7eb;border-radius:8px;padding:1rem;white-space:pre-wrap;overflow:auto}.modal{position:fixed;inset:0;background:rgba(15,23,42,.45);display:grid;place-items:center}.modal section{width:min(640px,90vw);background:white;border-radius:8px;padding:1rem}@media(max-width:900px){.app{grid-template-columns:1fr}.sidebar{position:sticky;top:0;z-index:1}.grid,.form,.metrics{grid-template-columns:1fr}}
</style>
