---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xin.an.
--- DateTime: 2026/8/4 14:13
---

local incrementValue = tonumber(ARGV[1])
local burstLimit = tonumber(ARGV[2])
local currentWindowWeight = tonumber(ARGV[3])
local totalThreshold = tonumber(ARGV[4])
local currentSubWindowIndex = tonumber(ARGV[5])
local expireTime = tonumber(ARGV[6])

local currentKeyIndex = currentSubWindowIndex + 1
local currentPeriodTotal = 0
local previousPeriodTotal = 0
local totalWeighted = 0

for i = 0, 9 do
    local keyIndex = i + 1
    local windowCount = tonumber(redis.call('GET', KEYS[keyIndex]) or '0')

    if windowCount > 0 then
        if i == currentSubWindowIndex then
            local weightedCount = windowCount * currentWindowWeight
            totalWeighted = totalWeighted + weightedCount
            currentPeriodTotal = currentPeriodTotal + weightedCount
        else
            totalWeighted = totalWeighted + windowCount
            local distance = (currentSubWindowIndex - i + 10) % 10
            if distance <= 4 then
                currentPeriodTotal = currentPeriodTotal + windowCount
            else
                previousPeriodTotal = previousPeriodTotal + windowCount
            end
        end
    end
end

local projectedIncrement = math.max(0, currentPeriodTotal - previousPeriodTotal) + incrementValue

if projectedIncrement > burstLimit and (totalWeighted + incrementValue) > totalThreshold then
    redis.call('EXPIRE', KEYS[currentKeyIndex], expireTime)
    return -math.floor(projectedIncrement)
end

local newCount = redis.call('INCRBY', KEYS[currentKeyIndex], incrementValue)
if newCount == incrementValue then
    redis.call('EXPIRE', KEYS[currentKeyIndex], expireTime)
end
return math.floor(totalWeighted + incrementValue)