server:
  port: 8888

spring:
  application:
    name: src
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: default-route
              uri: http://localhost:8859
              predicates:
                - Path=/**
